### ISSUE TITLE
Update with details from meeting 30-Mar-2022

### ISSUE THREAD

**Issue by johnelbasha** [johnelbasha/continuous_proffessional_development#2]
Update with the following notes from my mentoring meeting on 30-Mar-2022 with David Jones. 

1. Read through the Dockerfile definitions for several of our rails microservices

2. Read through the docker-compose.yml file that in our the edgepetrol-rest-proxy codebase, as this explains how multiple docker container should be run alongside each other, as well as the dependencies between those containers, any ports that are forwarded from docker to your localhost and potentially any volumes that need to be mounted from your localhost into the docker container.

3. Get comfortable with mounting volumes inside docker containers so that your code is being run, rather than the code that was compiled into a docker image .

```
admin-service:
    # image: 770537037907.dkr.ecr.eu-west-1.amazonaws.com/admin-service:latest
    build:
      context: ../admin-service
      args:
        GITHUB_API_TOKEN: <your-github-token-goes-here>
    volumes:
      - ../admin-service/:/admin-service
```
4. Make a minimal rails application (even just hello world). Make your rails app dependent on a postgresql database and an instance of redis . Create a Dockerfile  that'll bundle your rails app into a docker image. Write a docker-compose.yml file that defines 3 services; your dockerised rails app, a postgresql container and a redis container. Start the composition locally (docker-compose up) and verify that your app can be reached on your localhost and that it can successfully communicate with the postgresql and redis containers. (edited)
